const MEDIA = [

    // ═══════════════════════════════
    //  FILMS
    // ═══════════════════════════════
    { id: "m1", title: "Everything Everywhere All At Once", type: "Film", contributor: "Pedro", main_genre: "Action", sub_genres: ["Fantastique", "Aventure", "Comédie"], main_emotion: "Altruisme", complexity: 3, ambiance: "Chaotique", public: "Famille", favorite: true, pitch: "Une jeune femme se retrouve entraînée dans une aventure folle à travers le multivers pour sauver le monde.", platform: "Amazon Prime" },
    { id: "m2", title: "The Man From Earth", type: "Film", contributor: "Enola", main_genre: "SF", sub_genres: ["Drame", "Philosophique"], main_emotion: "Cérébral", complexity: 5, ambiance: "Tendu", public: "Solo", favorite: true, pitch: "Un professeur d'université annonce à ses collègues qu'il est immortel.", platform: "Youtube" },
    { id: "m3", title: "Arco", type: "Film", contributor: "Crepu", main_genre: "Fantastique", sub_genres: ["Aventure"], main_emotion: "Altruisme", complexity: 3, ambiance: "Poétique", public: "Famille", favorite: true, pitch: "Une aventure onirique et visuellement splendide.", platform: "Amazon Prime" },

    { id: "m4", title: "A Serbian Film", type: "Film", contributor: "Pedro", main_genre: "Horreur", sub_genres: ["Thriller", "Extrême"], main_emotion: "Choc", complexity: 4, ambiance: "Intense", public: "Solo", favorite: false, pitch: "Un acteur porno à la retraite accepte un dernier contrat sans en connaître la nature réelle.", platform: "" },
    { id: "m5", title: "DogMan", type: "Film", contributor: "Pedro", main_genre: "Drame", sub_genres: ["Crime", "Thriller"], main_emotion: "Empathie", complexity: 3, ambiance: "Sombre", public: "Solo", favorite: false, pitch: "Élevé par des chiens après une enfance traumatisante, un homme construit sa propre identité entre lumière et violence.", platform: "" },
    { id: "m6", title: "Imitation Game", type: "Film", contributor: "Pedro", main_genre: "Biopic", sub_genres: ["Historique", "Drame"], main_emotion: "Cérébral", complexity: 3, ambiance: "Tendu", public: "Solo", favorite: false, pitch: "Alan Turing et son équipe tentent de déchiffrer le code Enigma des nazis pendant la Seconde Guerre mondiale.", platform: "Netflix" },
    { id: "m7", title: "Seven", type: "Film", contributor: "Pedro", main_genre: "Thriller", sub_genres: ["Crime", "Policier"], main_emotion: "Intense", complexity: 3, ambiance: "Sombre", public: "Solo", favorite: false, pitch: "Deux détectives traquent un tueur en série qui met en scène ses meurtres autour des sept péchés capitaux.", platform: "" },
    { id: "m8", title: "A Cure for Wellness", type: "Film", contributor: "Pedro", main_genre: "Horreur", sub_genres: ["Thriller", "Mystère"], main_emotion: "Anxiété", complexity: 4, ambiance: "Mystérieux", public: "Solo", favorite: false, pitch: "Un jeune cadre envoyé récupérer son PDG dans un sanatorium suisse découvre que personne n'en ressort indemne.", platform: "" },
    { id: "m9", title: "Amsterdam", type: "Film", contributor: "Pedro", main_genre: "Comédie", sub_genres: ["Policier", "Historique"], main_emotion: "Drôle", complexity: 3, ambiance: "Légère", public: "Groupe", favorite: false, pitch: "Trois amis inséparables se retrouvent mêlés à un complot politique dans l'Amérique des années 30.", platform: "" },
    { id: "m10", title: "Escape Room", type: "Film", contributor: "Pedro", main_genre: "Thriller", sub_genres: ["Horreur", "Survival"], main_emotion: "Anxiété", complexity: 2, ambiance: "Tendu", public: "Groupe", favorite: false, pitch: "Six inconnus invités dans un escape room grandeur nature réalisent que les pièges sont bien réels.", platform: "Netflix" },
    { id: "m11", title: "La Colline a des Yeux", type: "Film", contributor: "Pedro", main_genre: "Horreur", sub_genres: ["Survival", "Slasher"], main_emotion: "Peur", complexity: 2, ambiance: "Intense", public: "Solo", favorite: false, pitch: "Une famille américaine tombe en panne dans le désert du Nouveau-Mexique et devient la cible de mutants cannibales.", platform: "" },
    { id: "m12", title: "Midsommar", type: "Film", contributor: "Pedro", main_genre: "Horreur", sub_genres: ["Folk Horror", "Drame"], main_emotion: "Anxiété", complexity: 4, ambiance: "Dépaysant", public: "Solo", favorite: false, pitch: "Un groupe d'amis participe à un festival folk suédois qui ne se déroule pas tout à fait comme prévu.", platform: "Amazon Prime" },
    { id: "m13", title: "Moi Capitaine", type: "Film", contributor: "Pedro", main_genre: "Drame", sub_genres: ["Migrant", "Aventure"], main_emotion: "Empathie", complexity: 3, ambiance: "Intense", public: "Solo", favorite: false, pitch: "Deux jeunes Sénégalais traversent le Sahara et la Méditerranée pour atteindre l'Europe et leurs rêves.", platform: "" },
    { id: "m14", title: "The Killers of the Flower Moon", type: "Film", contributor: "Pedro", main_genre: "Drame", sub_genres: ["Historique", "Crime", "Western"], main_emotion: "Choc", complexity: 4, ambiance: "Sombre", public: "Solo", favorite: false, pitch: "Dans l'Oklahoma des années 20, les membres de la tribu Osage disparaissent les uns après les autres après la découverte de pétrole sur leurs terres.", platform: "Apple TV+" },
    { id: "m15", title: "Sister Act", type: "Film", contributor: "Pedro", main_genre: "Comédie", sub_genres: ["Musique"], main_emotion: "Drôle", complexity: 1, ambiance: "Feel-good", public: "Famille", favorite: false, pitch: "Planquée par la police dans un couvent, une chanteuse de Vegas révolutionne la chorale de religières avec de la soul.", platform: "" },


    // ═══════════════════════════════
    //  SÉRIES
    // ═══════════════════════════════
    { id: "s1", title: "The Bear", type: "Série", contributor: "Crepu", main_genre: "Comédie dramatique", sub_genres: ["Cuisine", "Tranche de vie"], main_emotion: "Intense", complexity: 4, ambiance: "Bruyante", public: "Solo", favorite: true, pitch: " Un gars reprend le restaurant de son frère décédé.", platform: "Disney +" },


    // ═══════════════════════════════
    //  LIVRES
    // ═══════════════════════════════
    { id: "b1", title: "Les Thanatonautes", type: "Livre", creator: "Bernard Werber", contributor: "Pedro", main_genre: "Aventure", sub_genres: ["Philosophie", "Voyage", "SF"], main_emotion: "Philosophique", complexity: 5, ambiance: "Mystérieux", public: "Solo", favorite: true, pitch: "Des explorateurs de l'au-delà cartographiant le monde des morts" },


    // ═══════════════════════════════
    //  MUSIQUE
    // ═══════════════════════════════
    { id: "mu1", title: "As the world caves in", type: "Musique", creator: "Matt Maltese", contributor: "Pedro", main_genre: "Indie-Pop", sub_genres: ["Drame"], main_emotion: "Solitude", complexity: 3, ambiance: "Dramatique", public: "Solo", favorite: true, pitch: "Déclaration d'amour pendant la fin du monde" },


    // ═══════════════════════════════
    //  JEUX VIDÉO
    // ═══════════════════════════════
    { id: "g1", title: "Stacklands", type: "Jeu Vidéo", contributor: "Pedro", main_genre: "Gestion", sub_genres: ["Cartes"], main_emotion: "Optimisation", complexity: 2, ambiance: "Chill", public: "Solo", favorite: true, pitch: "Gérez votre village de cartes" },
    { id: "g2", title: "Hades", type: "Jeu Vidéo", contributor: "Pedro", main_genre: "Roguelite", sub_genres: ["Action", "Mythologie"], main_emotion: "Intense", complexity: 3, ambiance: "Tendu", public: "Solo", favorite: false, pitch: "Le fils du dieu des Enfers tente de s'échapper du royaume des morts en affrontant des légions de monstres.", platform: "PC/Switch/PS5" },
    { id: "g3", title: "Stardew Valley", type: "Jeu Vidéo", contributor: "Pedro", main_genre: "Simulation", sub_genres: ["Gestion", "RPG"], main_emotion: "Altruisme", complexity: 2, ambiance: "Chill", public: "Solo", favorite: false, pitch: "Héritez d'une ferme abandonnée et reconstruisez une vie à la campagne au rythme des saisons.", platform: "PC/Switch" },
    { id: "g4", title: "Balatro", type: "Jeu Vidéo", contributor: "Pedro", main_genre: "Roguelite", sub_genres: ["Cartes", "Poker"], main_emotion: "Optimisation", complexity: 3, ambiance: "Chill", public: "Solo", favorite: false, pitch: "Construisez des mains de poker absurdes et explosives grâce à des jokers et des modificateurs de plus en plus fous.", platform: "PC/Switch/PS5" },
    { id: "g5", title: "Dungeons and Dangerous Gambler", type: "Jeu Vidéo", contributor: "Pedro", main_genre: "Roguelite", sub_genres: ["Cartes", "Dungeon Crawl"], main_emotion: "Optimisation", complexity: 3, ambiance: "Chaotique", public: "Solo", favorite: false, pitch: "Explorez des donjons en construisant une main gagnante à chaque pièce.", platform: "PC" },


    // ═══════════════════════════════
    //  JEUX DE SOCIÉTÉ
    // ═══════════════════════════════
    { id: "bg1", title: "Cryptid", type: "Jeu de Société", contributor: "Pedro", main_genre: "Logique", sub_genres: ["Enquête"], main_emotion: "Deduction", complexity: 3, ambiance: "Mystérieux", public: "Groupe", favorite: false, pitch: "Trouvez le cryptide en vous basant sur des indices cryptiques" },
    { id: "bg2", title: "Princesse Rebelle", type: "Jeu de Société", contributor: "Crepu", main_genre: "Plis", sub_genres: ["Bluff", "Féminisme"], main_emotion: "Drôle", complexity: 3, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Jeu de plis dont le but est de ne pas se marier avec des princes ! (ENORME)" },

    { id: "bg3", title: "Harmonies", type: "Jeu de Société", contributor: "Pedro", main_genre: "Placement", sub_genres: ["Tuiles", "Nature"], main_emotion: "Zen", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Combinez des jetons de nature pour créer des habitats cohérents et marquer des points selon vos objectifs secrets." },
    { id: "bg4", title: "Ex Libris", type: "Jeu de Société", contributor: "Pedro", main_genre: "Gestion", sub_genres: ["Cartes", "Drafting"], main_emotion: "Cérébral", complexity: 3, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Constituez la meilleure bibliothèque de la ville en recrutant des assistants gnomes et en dénichant des livres rares." },
    { id: "bg5", title: "Pentacle", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Stratégie", "Abstrait"], main_emotion: "Cérébral", complexity: 3, ambiance: "Tendu", public: "Groupe", favorite: false, pitch: "Maîtrisez les cinq éléments magiques pour former des pentacles et dominer vos adversaires." },
    { id: "bg6", title: "Akropolis", type: "Jeu de Société", contributor: "Pedro", main_genre: "Placement", sub_genres: ["Tuiles", "Stratégie"], main_emotion: "Optimisation", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Construisez une cité grecque en empilant des tuiles : les quartiers surélevés rapportent plus de points." },
    { id: "bg7", title: "Point City", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Drafting", "Collection"], main_emotion: "Optimisation", complexity: 2, ambiance: "Chill", public: "Famille", favorite: false, pitch: "Piochez des cartes de ressources et de bâtiments pour construire la cité la plus efficace." },
    { id: "bg8", title: "Kelp", type: "Jeu de Société", contributor: "Pedro", main_genre: "Stratégie", sub_genres: ["Asymétrique", "2 joueurs"], main_emotion: "Intense", complexity: 3, ambiance: "Tendu", public: "Duo", favorite: false, pitch: "Un joueur incarne une pieuvre qui se cache dans une forêt de kelp, l'autre un requin blanc qui la traque." },
    { id: "bg9", title: "Commander of Nature", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Stratégie", "Nature"], main_emotion: "Optimisation", complexity: 3, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Maîtrisez les forces de la nature pour imposer votre domination sur le monde sauvage." },
    { id: "bg10", title: "Munchkin", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Humour", "Dungeon Crawl"], main_emotion: "Drôle", complexity: 2, ambiance: "Chaotique", public: "Groupe", favorite: false, pitch: "Explorez des donjons, battez des monstres ridicules, trahissez vos amis et montez de niveau — le premier à 10 gagne." },
    { id: "bg11", title: "Boreal", type: "Jeu de Société", contributor: "Pedro", main_genre: "Placement", sub_genres: ["Nature", "Tuiles"], main_emotion: "Zen", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Construisez et développez un écosystème nordique en posant des tuiles d'animaux et de paysages." },
    { id: "bg12", title: "Dracula vs Van Helsing", type: "Jeu de Société", contributor: "Pedro", main_genre: "Stratégie", sub_genres: ["Asymétrique", "2 joueurs", "Horreur"], main_emotion: "Intense", complexity: 3, ambiance: "Tendu", public: "Duo", favorite: false, pitch: "Un joueur incarne Dracula tentant de semer ses traces dans l'Europe nocturne, l'autre Van Helsing à ses trousses." },
    { id: "bg13", title: "Far Away", type: "Jeu de Société", contributor: "Pedro", main_genre: "Coopératif", sub_genres: ["Exploration", "Aventure"], main_emotion: "Altruisme", complexity: 3, ambiance: "Mystérieux", public: "Groupe", favorite: false, pitch: "Explorez ensemble un continent inconnu, cartographiez ses mystères et survivez à ses dangers." },
    { id: "bg14", title: "Let's Dig for Treasure", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Famille", "Chance"], main_emotion: "Drôle", complexity: 1, ambiance: "Chill", public: "Famille", favorite: false, pitch: "Fouillez la terre carte par carte à la recherche de trésors enfouis — simple, rapide, parfait pour toute la famille." },
    { id: "bg15", title: "Trou Noir", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Ambiance", "Push Your Luck"], main_emotion: "Drôle", complexity: 1, ambiance: "Chaotique", public: "Groupe", favorite: false, pitch: "Jouez des cartes en cherchant à éviter d'être aspiré par le trou noir — le dernier en lice a perdu." },
    { id: "bg16", title: "Let's Summon Demons", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Humour", "Horreur"], main_emotion: "Drôle", complexity: 1, ambiance: "Chaotique", public: "Groupe", favorite: false, pitch: "Invoquez des démons en jouant des cartes rituelles — un party game maléfique et hilarant." },
    { id: "bg17", title: "Don't Talk to Strangers", type: "Jeu de Société", contributor: "Pedro", main_genre: "Social", sub_genres: ["Bluff", "Communication"], main_emotion: "Drôle", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Faites deviner des mots à votre équipe en contournant des interdits de communication — sans jamais parler directement." },
    { id: "bg18", title: "Courtisans", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Bluff", "Déduction"], main_emotion: "Intense", complexity: 2, ambiance: "Tendu", public: "Groupe", favorite: false, pitch: "Manœuvrez dans les coulisses de la cour pour placer vos alliés aux postes les plus influents." },
    { id: "bg19", title: "Citadelle", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Bluff", "Stratégie", "Rôles"], main_emotion: "Cérébral", complexity: 3, ambiance: "Tendu", public: "Groupe", favorite: false, pitch: "Choisissez secrètement un personnage chaque tour pour construire des quartiers et saboter la ville de vos rivaux." },
    { id: "bg20", title: "Vale of Eternity", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Drafting", "Fantastique", "Collection"], main_emotion: "Cérébral", complexity: 3, ambiance: "Mystérieux", public: "Groupe", favorite: false, pitch: "Recrutez des créatures mythiques via un draft en temps réel et construisez un royaume de légende." },
    { id: "bg21", title: "Wyrmspan", type: "Jeu de Société", contributor: "Pedro", main_genre: "Gestion", sub_genres: ["Moteur", "Dragons", "Collection"], main_emotion: "Optimisation", complexity: 4, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Découvrez et attirez des dragons dans vos excavations pour construire un sanctuaire reptilien d'exception." },
    { id: "bg22", title: "Love Letter", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Déduction", "Bluff"], main_emotion: "Intense", complexity: 1, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Seize cartes, des éliminations en chaîne, et un seul objectif : faire parvenir votre lettre à la princesse." },
    { id: "bg23", title: "Trio", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Mémoire", "Collection"], main_emotion: "Drôle", complexity: 1, ambiance: "Chill", public: "Famille", favorite: false, pitch: "Trouvez trois cartes identiques avant vos adversaires en fouilant les mains et la pioche — mémorisation pure." },
    { id: "bg24", title: "Pappayoo", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Plis", "Famille"], main_emotion: "Drôle", complexity: 2, ambiance: "Chill", public: "Famille", favorite: false, pitch: "Jeu de plis pour toute la famille où il vaut mieux éviter de ramasser le redoutable Pappayoo." },
    { id: "bg25", title: "Galerapagos", type: "Jeu de Société", contributor: "Pedro", main_genre: "Coopératif", sub_genres: ["Survie", "Négociation", "Trahison"], main_emotion: "Intense", complexity: 3, ambiance: "Tendu", public: "Groupe", favorite: false, pitch: "Naufragés sur une île déserte, construisez ensemble un radeau pour fuir — mais il ne peut pas embarquer tout le monde." },
    { id: "bg26", title: "Luz", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Stratégie", "Abstrait"], main_emotion: "Cérébral", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Orchestrez lumières et ombres pour dominer le plateau dans ce jeu d'abstraction délicat." },
    { id: "bg27", title: "Complots", type: "Jeu de Société", contributor: "Pedro", main_genre: "Bluff", sub_genres: ["Social", "Déduction", "Rôles"], main_emotion: "Intense", complexity: 2, ambiance: "Tendu", public: "Groupe", favorite: false, pitch: "Deux cartes en main, une seule règle : mentez, manipulez, éliminez vos rivaux jusqu'à rester le dernier debout." },
    { id: "bg28", title: "Mysterium", type: "Jeu de Société", contributor: "Pedro", main_genre: "Coopératif", sub_genres: ["Déduction", "Fantastique", "Communication"], main_emotion: "Cérébral", complexity: 3, ambiance: "Mystérieux", public: "Groupe", favorite: false, pitch: "Un fantôme silencieux guide des médiums via des visions oniriques pour résoudre son propre meurtre." },
    { id: "bg29", title: "Decrypto", type: "Jeu de Société", contributor: "Pedro", main_genre: "Mots", sub_genres: ["Coopératif", "Codes", "Équipes"], main_emotion: "Drôle", complexity: 2, ambiance: "Chaotique", public: "Groupe", favorite: false, pitch: "Transmettez un code à votre équipe sans que l'adversaire n'intercepte vos indices — deux niveaux de contre-espionnage." },
    { id: "bg30", title: "Splendor", type: "Jeu de Société", contributor: "Pedro", main_genre: "Stratégie", sub_genres: ["Gestion", "Collection", "Moteur"], main_emotion: "Optimisation", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Collectez des gemmes pour acheter des mines et des commerces — construisez le moteur de ressources le plus efficace." },
    { id: "bg31", title: "Spicy", type: "Jeu de Société", contributor: "Pedro", main_genre: "Bluff", sub_genres: ["Cartes", "Ambiance"], main_emotion: "Drôle", complexity: 1, ambiance: "Chaotique", public: "Groupe", favorite: false, pitch: "Annoncez une carte plus haute que la précédente — mais rien ne vous oblige à dire la vérité." },
    { id: "bg32", title: "Emblèmes", type: "Jeu de Société", contributor: "Pedro", main_genre: "Cartes", sub_genres: ["Stratégie", "Collection"], main_emotion: "Optimisation", complexity: 2, ambiance: "Chill", public: "Groupe", favorite: false, pitch: "Collectionnez et combinez des emblèmes pour former des combinaisons gagnantes et construire votre héraldique." },

];
