const CITY_CONFIG = { lat: 43.6047, lng: 1.4442, zoom: 13 };

const CITIES = {
  'Toulouse': { lat: 43.6047, lng: 1.4442, zoom: 14 },
  'Madrid':   { lat: 40.4168, lng: -3.7038, zoom: 13 },
  'Paris':    { lat: 48.8566, lng: 2.3522,  zoom: 13 },
};

const PLACES = [

  // ══════════════════════════════════════════
  //  TOULOUSE
  // ══════════════════════════════════════════
  {
    id: 'tlse_01', city: 'Toulouse',
    name: 'Bota Pub', type: 'Bar', neighborhood: 'Capitole',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Bar emblématique du centre. Ambiance chaleureuse, bonne sélection de bières et clientèle sympa. Classique des soirées toulousaines.',
    address: 'Toulouse – Capitole', lat: 43.6068, lng: 1.4428,
    hours: '–', tags: ['Bières', 'Convivial', 'Centre'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_02', city: 'Toulouse',
    name: 'Zig Zag', type: 'Bar', neighborhood: 'Centre',
    moods: ['Entre amis', 'Date'], budget: '€€',
    description: 'Bar très bien noté, ambiance soignée. Petit endroit attachant, idéal pour un verre en bonne compagnie.',
    address: 'Toulouse – Centre', lat: 43.5994, lng: 1.4464,
    hours: '–', tags: ['Bar', 'Intimiste'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'tlse_03', city: 'Toulouse',
    name: 'Le Zinc', type: 'Restaurant', neighborhood: 'Centre',
    moods: ['Date', 'Tranquille'], budget: '€€',
    description: 'Restaurant très bien noté, cuisine soignée dans un cadre convivial. Belle adresse pour un repas de qualité sans se ruiner.',
    address: 'Toulouse – Centre', lat: 43.5988, lng: 1.4441,
    hours: '–', tags: ['Cuisine française', 'Rapport qualité-prix'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'tlse_04', city: 'Toulouse',
    name: 'Miya Fondue 米亚火锅', type: 'Restaurant', neighborhood: 'Centre',
    moods: ['Entre amis', 'Date'], budget: '€€',
    description: 'Hot pot chinois de grande qualité avec bouillons variés et produits frais. Excellent rapport qualité-prix, service attentionné.',
    address: 'Toulouse – Centre', lat: 43.5997, lng: 1.4453,
    hours: '–', tags: ['Hot pot', 'Chinois', 'Produits frais'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'tlse_05', city: 'Toulouse',
    name: 'Chez Molly', type: 'Restaurant', neighborhood: 'Montaudran',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Restaurant XXL à Montaudran spécialisé grillades et viandes. Portions généreuses, ambiance détendue, parfait pour un repas entre amis.',
    address: 'Toulouse – Montaudran', lat: 43.5696, lng: 1.4807,
    hours: '–', tags: ['Grillades', 'Grands formats', 'Montaudran'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_06', city: 'Toulouse',
    name: 'La Sandia', type: 'Restaurant', neighborhood: 'Centre',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Restaurant mexicain avec des plats authentiques et généreux. Ambiance colorée et chaleureuse, cocktails bien dosés.',
    address: 'Toulouse – Centre', lat: 43.6065, lng: 1.4478,
    hours: '–', tags: ['Mexicain', 'Cocktails', 'Coloré'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_07', city: 'Toulouse',
    name: 'Bep Chay', type: 'Restaurant', neighborhood: 'Centre',
    moods: ['Tranquille', 'Entre amis'], budget: '€',
    description: 'Restaurant végétarien vietnamien remarquablement bien noté. Cuisine fraîche, goûteuse et abordable. Une des meilleures adresses végé de la ville.',
    address: 'Toulouse – Centre', lat: 43.5982, lng: 1.4448,
    hours: '–', tags: ['Végétarien', 'Vietnamien', 'Sain'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'tlse_08', city: 'Toulouse',
    name: 'L\'Entrecôte', type: 'Restaurant', neighborhood: 'Wilson',
    moods: ['Date', 'Entre amis'], budget: '€€',
    description: 'L\'institution toulousaine. Une seule formule : salade, entrecôte sauce secrète, frites à volonté. File d\'attente mais ça vaut le coup.',
    address: 'Toulouse – Wilson', lat: 43.5968, lng: 1.4432,
    hours: 'Lun–Dim 12h–14h / 19h–23h', tags: ['Institution', 'Entrecôte', 'Sauce secrète'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_09', city: 'Toulouse',
    name: 'Fat Cat', type: 'Cocktail', neighborhood: 'Capitole',
    moods: ['Date', 'Entre amis'], budget: '€',
    description: 'Bar à cocktails incontournable du centre avec une belle carte et des bartenders passionnés. Rapport qualité-prix excellent.',
    address: 'Toulouse – Capitole', lat: 43.6040, lng: 1.4436,
    hours: '–', tags: ['Cocktails', 'Atmosphère', 'Abordable'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_10', city: 'Toulouse',
    name: 'LIGOT', type: 'Restaurant', neighborhood: 'Capitole',
    moods: ['Date', 'Tranquille'], budget: '€€',
    description: 'Restaurant bien noté avec une cuisine soignée et créative. Cadre agréable, bon service.',
    address: 'Toulouse – Capitole', lat: 43.6046, lng: 1.4444,
    hours: '–', tags: ['Cuisine créative', 'Soigné'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_11', city: 'Toulouse',
    name: 'Curry Café', type: 'Restaurant', neighborhood: 'Centre',
    moods: ['Entre amis', 'Date'], budget: '€€',
    description: 'Restaurant indien très bien noté avec des currys généreux et parfumés. Service sympathique, cadre chaleureux.',
    address: 'Toulouse – Centre', lat: 43.6058, lng: 1.4451,
    hours: '–', tags: ['Indien', 'Curry', 'Épices'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'tlse_12', city: 'Toulouse',
    name: 'BOCA', type: 'Restaurant', neighborhood: 'Centre',
    moods: ['Entre amis', 'Date'], budget: '€€',
    description: 'Tapas espagnoles de haute volée. L\'une des meilleures adresses toulousaines avec une note et un nombre d\'avis impressionnants.',
    address: 'Toulouse – Centre', lat: 43.6010, lng: 1.4456,
    hours: '–', tags: ['Tapas', 'Espagnol', 'Partage'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'tlse_13', city: 'Toulouse',
    name: 'Musée des Abattoirs', type: 'Musée', neighborhood: 'Centre',
    moods: ['Entre amis', 'Date', 'Tranquille'], budget: '€',
    description:"L'exposition Jean-Charles de Castelbajac. L'imagination au pouvoir investit magistralement le musée des Abattoirs à Toulouse. C'est une rétrospective XXL de près de 300 œuvres qui retrace plus de cinquante ans de création d'un artiste inclassable, qui a toujours refusé de s'enfermer dans les frontières de la mode. Jusqu'à fin août 2026. Gratuit le premier dimanche du mois",
    address: 'Toulouse – Centre', lat: 43.3603, lng: 1.2546,
    hours: '–', tags: ['Émerveillement','Art'], highlight: true, contributor: 'Romain S',
  },

  // ══════════════════════════════════════════
  //  MADRID
  // ══════════════════════════════════════════

  // — Restaurants & Bars à manger —
  {
    id: 'mad_01', city: 'Madrid',
    name: 'El Jardín Secreto', type: 'Cocktail', neighborhood: 'Conde Duque',
    moods: ['Date', 'Entre amis'], budget: '€€',
    description: 'Bar à cocktails caché dans un cadre verdoyant et romantique du quartier Conde Duque. Atmosphère unique, idéal pour une soirée à deux.',
    address: 'Conde Duque, Madrid', lat: 40.4261, lng: -3.7112,
    hours: '–', tags: ['Jardin', 'Romantique', 'Cocktails'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_02', city: 'Madrid',
    name: 'TKO Tacos Iglesia', type: 'Restaurant', neighborhood: 'Malasaña',
    moods: ['Entre amis', 'Tranquille'], budget: '€€',
    description: 'Tacos mexicains de qualité dans le quartier Malasaña. Ingrédients frais, ambiance décontractée.',
    address: 'Malasaña, Madrid', lat: 40.4308, lng: -3.7022,
    hours: '–', tags: ['Mexicain', 'Tacos', 'Street food'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_03', city: 'Madrid',
    name: 'TKO Tacos Clavel', type: 'Restaurant', neighborhood: 'Chueca',
    moods: ['Entre amis', 'Tranquille'], budget: '€€',
    description: 'La seconde adresse TKO, en plein Chueca. Même qualité de tacos dans un quartier animé.',
    address: 'Chueca, Madrid', lat: 40.4219, lng: -3.6964,
    hours: '–', tags: ['Mexicain', 'Tacos', 'Chueca'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_04', city: 'Madrid',
    name: 'La Kama Café', type: 'Cocktail', neighborhood: 'Barrio de las Letras',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Bar à cocktails tropicaux avec ambiance festive. Décor exubérant, cocktails colorés et musique qui monte.',
    address: 'Barrio de las Letras, Madrid', lat: 40.4118, lng: -3.6997,
    hours: '–', tags: ['Tropical', 'Cocktails', 'Festif'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_05', city: 'Madrid',
    name: 'Jack\'s Library', type: 'Cocktail', neighborhood: 'Centro',
    moods: ['Date', 'Entre amis'], budget: '€€',
    description: 'Bar à cocktails avec décor bibliothèque très instagrammable. Carte créative et atmosphère feutrée.',
    address: 'Centro, Madrid', lat: 40.4189, lng: -3.7028,
    hours: '–', tags: ['Cocktails', 'Bibliothèque', 'Intimiste'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_06', city: 'Madrid',
    name: 'MAMVA', type: 'Cocktail', neighborhood: 'Chamberí',
    moods: ['Date', 'Entre amis'], budget: '€€',
    description: 'Bar à cocktails bien noté dans le quartier Chamberí. Ambiance soignée et carte originale.',
    address: 'Chamberí, Madrid', lat: 40.4278, lng: -3.6992,
    hours: '–', tags: ['Cocktails', 'Chamberí', 'Soigné'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_07', city: 'Madrid',
    name: 'Sky 44 Rooftop', type: 'Bar', neighborhood: 'Plaza de España',
    moods: ['Entre amis', 'Date'], budget: '€€',
    description: 'Bar en rooftop avec vue panoramique sur Madrid. Idéal au coucher du soleil pour un verre avec la skyline en fond.',
    address: 'Plaza de España, Madrid', lat: 40.4240, lng: -3.7115,
    hours: '–', tags: ['Rooftop', 'Vue panoramique', 'Coucher de soleil'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_08', city: 'Madrid',
    name: 'Parrilla el Gaucho', type: 'Restaurant', neighborhood: 'Gran Vía',
    moods: ['Entre amis', 'Date'], budget: '€€€',
    description: 'Grillades argentines de qualité sur la Gran Vía. Viandes sélectionnées, portions généreuses.',
    address: 'Gran Vía, Madrid', lat: 40.4200, lng: -3.7058,
    hours: '–', tags: ['Grillades', 'Argentin', 'Viandes'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_09', city: 'Madrid',
    name: 'Gracias Padre', type: 'Restaurant', neighborhood: 'Chueca',
    moods: ['Entre amis', 'Brunch'], budget: '€€',
    description: 'Restaurant mexicain végétarien branché de Chueca. Décor jungle tropical, tacos créatifs et mezcal de qualité.',
    address: 'Chueca, Madrid', lat: 40.4222, lng: -3.6971,
    hours: '–', tags: ['Mexicain', 'Végétarien', 'Trendy'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_10', city: 'Madrid',
    name: 'El Tigre Sidra Bar', type: 'Bar', neighborhood: 'Centro',
    moods: ['Entre amis', 'Festif'], budget: '€',
    description: 'Célèbre bar à tapas où les consommations s\'accompagnent d\'une assiette garnie. Ambiance bruyante et festive, parfait pour commencer la soirée.',
    address: 'Centro, Madrid', lat: 40.4197, lng: -3.7005,
    hours: '–', tags: ['Tapas offertes', 'Ambiance', 'Pas cher'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_11', city: 'Madrid',
    name: 'Ojalá', type: 'Restaurant', neighborhood: 'Malasaña',
    moods: ['Brunch', 'Tranquille'], budget: '€€',
    description: 'Restaurant avec terrasse intérieure à sable à Malasaña. Brunch très réputé, cadre décontracté et original.',
    address: 'Malasaña, Madrid', lat: 40.4248, lng: -3.7042,
    hours: '–', tags: ['Brunch', 'Original', 'Malasaña'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_12', city: 'Madrid',
    name: 'ANTONIA PIZZA', type: 'Restaurant', neighborhood: 'Chamberí',
    moods: ['Entre amis', 'Tranquille'], budget: '€',
    description: 'Pizzeria à emporter très bien notée. Pâtes légères et croustillantes, ingrédients de qualité.',
    address: 'Chamberí, Madrid', lat: 40.4290, lng: -3.6990,
    hours: '–', tags: ['Pizza', 'À emporter', 'Rapport qualité-prix'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_13', city: 'Madrid',
    name: 'HEMU Sushi Buffet', type: 'Restaurant', neighborhood: 'Centro',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Buffet de sushis à volonté avec une belle variété de pièces fraîches. Bon rapport quantité-qualité.',
    address: 'Centro, Madrid', lat: 40.4182, lng: -3.7008,
    hours: '–', tags: ['Sushis', 'Buffet', 'À volonté'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_14', city: 'Madrid',
    name: 'Bodega de la Ardosa', type: 'Bar', neighborhood: 'Malasaña',
    moods: ['Tranquille', 'Entre amis'], budget: '€€',
    description: 'Vieille taverne madrilène emblématique avec barils en bois et vermut maison. Incontournable pour ressentir l\'âme de Madrid.',
    address: 'Malasaña, Madrid', lat: 40.4251, lng: -3.7039,
    hours: '–', tags: ['Vermut', 'Historique', 'Taverne'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_15', city: 'Madrid',
    name: 'El Capricho Extremeño', type: 'Restaurant', neighborhood: 'Lavapiés',
    moods: ['Tranquille', 'Entre amis'], budget: '€',
    description: 'Petite taverne traditionnelle de Lavapiés proposant des tapas extremeñas généreuses à prix mini. Authentique et sans chichis.',
    address: 'Lavapiés, Madrid', lat: 40.4099, lng: -3.7012,
    hours: '–', tags: ['Tapas', 'Traditionnel', 'Pas cher'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_16', city: 'Madrid',
    name: 'Pez Tortilla', type: 'Bar', neighborhood: 'Malasaña',
    moods: ['Entre amis', 'Brunch'], budget: '€',
    description: 'Bar iconique de Malasaña réputé pour sa tortilla de patatas. Ambiance typique de quartier, très fréquenté le week-end.',
    address: 'Malasaña, Madrid', lat: 40.4255, lng: -3.7046,
    hours: '–', tags: ['Tortilla', 'Tapas', 'Emblématique'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_17', city: 'Madrid',
    name: 'Taberna el Buo', type: 'Bar', neighborhood: 'Centro',
    moods: ['Tranquille', 'Entre amis'], budget: '€€',
    description: 'Taverne madrilène classique avec ambiance de quartier et cuisine traditionnelle. Bon endroit pour découvrir la gastronomie locale.',
    address: 'Centro, Madrid', lat: 40.4268, lng: -3.6993,
    hours: '–', tags: ['Taverne', 'Traditionnel', 'Cuisine locale'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_18', city: 'Madrid',
    name: 'Inclan Brutal Bar', type: 'Restaurant', neighborhood: 'Barrio de las Letras',
    moods: ['Date', 'Entre amis'], budget: '€€€',
    description: 'Restaurant gastronomique bien noté dans le Barrio de las Letras. Cuisine créative et travaillée dans un cadre design.',
    address: 'Barrio de las Letras, Madrid', lat: 40.4106, lng: -3.7008,
    hours: '–', tags: ['Gastronomique', 'Créatif', 'Design'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_19', city: 'Madrid',
    name: 'Picalagartos · Azotea Bar', type: 'Bar', neighborhood: 'Gran Vía',
    moods: ['Date', 'Entre amis'], budget: '€€',
    description: 'Bar en rooftop sur la Gran Vía avec une vue imprenable sur les toits de Madrid. Cocktails et tapas à partager.',
    address: 'Gran Vía 50, Madrid', lat: 40.4204, lng: -3.7071,
    hours: '–', tags: ['Rooftop', 'Gran Vía', 'Vue spectaculaire'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_20', city: 'Madrid',
    name: 'NEXT LEVEL BAR Arcade', type: 'Bar', neighborhood: 'Chueca',
    moods: ['Entre amis', 'Festif'], budget: '€',
    description: 'Bar arcade avec jeux vidéo rétro et ambiance geek décomplexée. Cocktails et bières pendant que tu joues.',
    address: 'Chueca, Madrid', lat: 40.4225, lng: -3.6972,
    hours: '–', tags: ['Arcade', 'Jeux rétro', 'Geek'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_21', city: 'Madrid',
    name: 'Chocolatería San Ginés', type: 'Café', neighborhood: 'Centro',
    moods: ['Brunch', 'Tranquille'], budget: '€',
    description: 'Institution madrilène ouverte depuis 1894. Churros et chocolat chaud épais à toute heure, y compris à 4h du matin après une soirée.',
    address: 'Pasadizo San Ginés, Madrid', lat: 40.4176, lng: -3.7064,
    hours: 'Lun–Dim 24h/24', tags: ['Churros', 'Chocolat chaud', 'Institution', '24h/24'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_22', city: 'Madrid',
    name: 'La Pollería Madrid', type: 'Café', neighborhood: 'Malasaña',
    moods: ['Brunch', 'Tranquille'], budget: '€€',
    description: 'Boutique-café spécialisée dans les desserts originaux et créatifs. Lieu tendance de Malasaña à tester.',
    address: 'Malasaña, Madrid', lat: 40.4253, lng: -3.7036,
    hours: '–', tags: ['Desserts', 'Créatif', 'Tendance'], highlight: false, contributor: 'Pedro',
  },

  // — Clubs & Discothèques —
  {
    id: 'mad_23', city: 'Madrid',
    name: 'Calle 365', type: 'Club', neighborhood: 'Chueca',
    moods: ['Festif'], budget: '€€',
    description: 'Discothèque branchée de Chueca ouverte toute l\'année. Musique électronique et ambiance festive garantie.',
    address: 'Chueca, Madrid', lat: 40.4236, lng: -3.6990,
    hours: 'Jeu–Sam 23h–6h', tags: ['Électronique', 'Chueca', 'Festif'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_24', city: 'Madrid',
    name: 'Cuenca Club', type: 'Club', neighborhood: 'Centro',
    moods: ['Festif'], budget: '€€',
    description: 'Discothèque madrilène avec programmation variée et ambiance festive sur plusieurs niveaux.',
    address: 'Centro, Madrid', lat: 40.4235, lng: -3.6985,
    hours: 'Ven–Sam 23h–6h', tags: ['Discothèque', 'Ambiance'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_25', city: 'Madrid',
    name: 'MACERA CLUB', type: 'Club', neighborhood: 'Centro',
    moods: ['Festif'], budget: '€€',
    description: 'Club madrilène avec bar à cocktails et dance floor. Ambiance underground et programmation pointue.',
    address: 'Centro, Madrid', lat: 40.4175, lng: -3.7005,
    hours: 'Ven–Sam minuit–6h', tags: ['Cocktails', 'Underground', 'Dance floor'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_26', city: 'Madrid',
    name: 'OPIUM CLUB', type: 'Club', neighborhood: 'Retiro',
    moods: ['Festif'], budget: '€€€',
    description: 'Club haut de gamme de Madrid sur le Paseo del Prado. Musique commerciale et pop, clientèle select, entrée parfois difficile.',
    address: 'Paseo del Prado, Madrid', lat: 40.4108, lng: -3.6937,
    hours: 'Ven–Sam 23h–6h', tags: ['Haut de gamme', 'Commercial', 'Select'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_27', city: 'Madrid',
    name: 'Shoko Madrid', type: 'Club', neighborhood: 'Retiro',
    moods: ['Festif'], budget: '€€',
    description: 'Club avec terrasse extérieure ouvert l\'été sur le Paseo del Prado. Musique électronique et commerciale.',
    address: 'Paseo del Prado, Madrid', lat: 40.4107, lng: -3.6936,
    hours: 'Ven–Sam 23h–6h', tags: ['Terrasse été', 'Électronique', 'Prado'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_28', city: 'Madrid',
    name: 'Barceló Theatre', type: 'Club', neighborhood: 'Alonso Martínez',
    moods: ['Festif'], budget: '€€',
    description: 'Grande discothèque dans un théâtre reconverti, impressionnant décor victorien. Soirées thématiques et grandes têtes d\'affiche.',
    address: 'Alonso Martínez, Madrid', lat: 40.4271, lng: -3.6987,
    hours: 'Ven–Sam 23h–6h', tags: ['Théâtre reconverti', 'Grand format', 'Soirées thématiques'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_29', city: 'Madrid',
    name: 'Sala La Riviera', type: 'Spectacle', neighborhood: 'Madrid Río',
    moods: ['Culture', 'Festif'], budget: '€€',
    description: 'Salle de concerts mythique de Madrid au bord du Manzanares. Concerts rock, électro et pop, terrasse extérieure en été.',
    address: 'Madrid Río, Madrid', lat: 40.4059, lng: -3.7163,
    hours: 'Selon programme', tags: ['Concerts', 'Rock', 'Terrasse'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_30', city: 'Madrid',
    name: 'Savoy Club', type: 'Club', neighborhood: 'Chueca',
    moods: ['Festif'], budget: '€',
    description: 'Club événementiel de Chueca avec soirées thématiques régulières. Petit format, ambiance chaleureuse.',
    address: 'Chueca, Madrid', lat: 40.4225, lng: -3.6975,
    hours: 'Selon programme', tags: ['Soirées thématiques', 'Petit format'], highlight: false, contributor: 'Pedro',
  },

  // — Musées —
  {
    id: 'mad_31', city: 'Madrid',
    name: 'Musée du Prado', type: 'Musée', neighborhood: 'Paseo del Arte',
    moods: ['Culture', 'Tranquille'], budget: '€€',
    description: 'L\'un des plus grands musées du monde. Velázquez, Goya, Rubens, El Bosco… Une collection incomparable. Entrée gratuite 18h–20h du lun au sam.',
    address: 'Paseo del Prado, Madrid', lat: 40.4138, lng: -3.6921,
    hours: 'Lun–Sam 10h–20h, Dim 10h–19h', tags: ['Velázquez', 'Goya', 'Gratuit 18h'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_32', city: 'Madrid',
    name: 'Musée Reina Sofía', type: 'Musée', neighborhood: 'Paseo del Arte',
    moods: ['Culture', 'Tranquille'], budget: '€€',
    description: 'Art moderne et contemporain espagnol. Picasso, Dalí, Miró. Le Guernica y trône en majesté. Entrée gratuite lundi et après 19h.',
    address: 'Calle Santa Isabel, Madrid', lat: 40.4082, lng: -3.6937,
    hours: 'Lun 10h–14h30, Mer–Sam 10h–21h, Dim 10h–19h', tags: ['Guernica', 'Art moderne', 'Picasso'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_33', city: 'Madrid',
    name: 'Musée Thyssen-Bornemisza', type: 'Musée', neighborhood: 'Paseo del Arte',
    moods: ['Culture', 'Tranquille'], budget: '€€',
    description: 'Collection privée exceptionnelle couvrant 8 siècles de peinture. Complète parfaitement le Prado et la Reina Sofía pour former le triangle de l\'art.',
    address: 'Paseo del Prado, Madrid', lat: 40.4159, lng: -3.6949,
    hours: 'Mar–Dim 10h–19h', tags: ['Triangle de l\'art', 'Peinture', 'Collection privée'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_34', city: 'Madrid',
    name: 'CaixaForum Madrid', type: 'Musée', neighborhood: 'Paseo del Arte',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Centre culturel dans une ancienne centrale électrique reconvertie. Expos temporaires de qualité, entrée abordable et jardin vertical spectaculaire.',
    address: 'Paseo del Prado 36, Madrid', lat: 40.4097, lng: -3.6944,
    hours: 'Lun–Dim 10h–20h', tags: ['Expos temporaires', 'Jardin vertical', 'Architecture'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_35', city: 'Madrid',
    name: 'Museo Arqueológico Nacional', type: 'Musée', neighborhood: 'Colón',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Riche collection archéologique espagnole, de la préhistoire à l\'art islamique. La Dame d\'Elche y est exposée. Entrée gratuite le dimanche.',
    address: 'Calle Serrano, Madrid', lat: 40.4231, lng: -3.6887,
    hours: 'Mar–Sam 9h30–20h, Dim 9h30–15h', tags: ['Archéologie', 'Dame d\'Elche', 'Gratuit le dim'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_36', city: 'Madrid',
    name: 'Museo Geominero', type: 'Musée', neighborhood: 'Almagro',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Fascinant musée géologique avec des milliers de minéraux, fossiles et roches. Entrée gratuite, remarquablement bien noté.',
    address: 'Ríos Rosas 23, Madrid', lat: 40.4278, lng: -3.6934,
    hours: 'Lun–Ven 9h–14h / 16h–18h', tags: ['Géologie', 'Minéraux', 'Fossiles', 'Gratuit'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_37', city: 'Madrid',
    name: 'Museo Artes Decorativas', type: 'Musée', neighborhood: 'Retiro',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Arts décoratifs espagnols du Moyen-Âge au XXe siècle dans un beau palais près du Retiro. Collection de céramiques et mobilier remarquable.',
    address: 'Montalbán 12, Madrid', lat: 40.4158, lng: -3.6857,
    hours: 'Mar–Sam 9h30–15h, Dim 10h–15h', tags: ['Arts déco', 'Céramiques', 'Palais'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_38', city: 'Madrid',
    name: 'Musée d\'Histoire de Madrid', type: 'Musée', neighborhood: 'Malasaña',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Histoire de Madrid racontée en objets et documents. Entrée gratuite dans un palais baroque magnifique avec une porte churrigueresque à couper le souffle.',
    address: 'Fuencarral 78, Madrid', lat: 40.4281, lng: -3.7021,
    hours: 'Mar–Dim 10h–20h', tags: ['Gratuit', 'Baroque', 'Histoire de Madrid'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_39', city: 'Madrid',
    name: 'Académie Royale des Beaux-Arts', type: 'Musée', neighborhood: 'Centro',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Troisième musée de peinture de Madrid mais souvent oublié des touristes. Goya, Rubens, El Greco en toute tranquillité.',
    address: 'Calle Alcalá 13, Madrid', lat: 40.4166, lng: -3.7003,
    hours: 'Mar–Dim 10h–15h', tags: ['Goya', 'Sans foule', 'Peinture ancienne'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_40', city: 'Madrid',
    name: 'Musée du Romantisme', type: 'Musée', neighborhood: 'Malasaña',
    moods: ['Culture', 'Date'], budget: '€',
    description: 'Palais du XIXe siècle reconstitué tel qu\'une maison romantique de l\'époque. Atmosphère unique et intimiste, peu connu des touristes.',
    address: 'Calle San Mateo 13, Madrid', lat: 40.4266, lng: -3.7024,
    hours: 'Mar–Sam 9h30–18h30, Dim 10h–15h', tags: ['XIXe siècle', 'Intimiste', 'Romantique'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_41', city: 'Madrid',
    name: 'Palais de Velázquez', type: 'Musée', neighborhood: 'Retiro',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Beau palais en fer et brique dans le parc du Retiro, utilisé pour des expos d\'art contemporain temporaires. Entrée gratuite.',
    address: 'Parque del Retiro, Madrid', lat: 40.4167, lng: -3.6854,
    hours: 'Lun, Mer–Dim 10h–18h (été 10h–22h)', tags: ['Gratuit', 'Expos contemporaines', 'Retiro'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_42', city: 'Madrid',
    name: 'Musée du Ferrocarril', type: 'Musée', neighborhood: 'Delicias',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Musée ferroviaire dans l\'ancienne gare de Delicias. Locomotives à vapeur, wagons historiques et histoire des chemins de fer espagnols.',
    address: 'Paseo de las Delicias 61, Madrid', lat: 40.3987, lng: -3.6951,
    hours: 'Mar–Dim 10h–15h', tags: ['Trains', 'Locomotives', 'Histoire industrielle'], highlight: false, contributor: 'Pedro',
  },

  // — Spectacles & Culture —
  {
    id: 'mad_43', city: 'Madrid',
    name: 'Teatro Albéniz Madrid', type: 'Spectacle', neighborhood: 'Centro',
    moods: ['Culture', 'Date'], budget: '€€',
    description: 'Théâtre historique du centre de Madrid avec programmation variée : danse, musique, théâtre contemporain.',
    address: 'Centro, Madrid', lat: 40.4183, lng: -3.7020,
    hours: 'Selon programme', tags: ['Théâtre', 'Danse', 'Musique'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_44', city: 'Madrid',
    name: 'La Estación Gran Teatro', type: 'Spectacle', neighborhood: 'Príncipe Pío',
    moods: ['Culture', 'Entre amis'], budget: '€€',
    description: 'Grande salle de spectacles dans l\'ancienne gare de Príncipe Pío. Comédies musicales, concerts et shows grand format.',
    address: 'Príncipe Pío, Madrid', lat: 40.4218, lng: -3.7196,
    hours: 'Selon programme', tags: ['Comédie musicale', 'Gare reconvertie', 'Grand format'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_45', city: 'Madrid',
    name: 'Théâtre Calderón', type: 'Spectacle', neighborhood: 'Atocha',
    moods: ['Culture', 'Date'], budget: '€€',
    description: 'Théâtre classique madrilène avec programmation de comédie musicale et spectacles grand public.',
    address: 'Calle Atocha, Madrid', lat: 40.4131, lng: -3.6973,
    hours: 'Selon programme', tags: ['Comédie musicale', 'Classique', 'Madrid'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_46', city: 'Madrid',
    name: 'Teatro Infanta Isabel', type: 'Spectacle', neighborhood: 'Barrio de las Letras',
    moods: ['Culture', 'Date'], budget: '€€',
    description: 'Petit théâtre historique spécialisé dans la comédie. Programmation légère et accessible.',
    address: 'Barrio de las Letras, Madrid', lat: 40.4119, lng: -3.6953,
    hours: 'Selon programme', tags: ['Comédie', 'Théâtre', 'Intime'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_47', city: 'Madrid',
    name: 'Teatro Gran Vía', type: 'Spectacle', neighborhood: 'Gran Vía',
    moods: ['Culture', 'Entre amis'], budget: '€€',
    description: 'Grande salle de spectacles sur la Gran Vía, programmation principalement comédies musicales populaires.',
    address: 'Gran Vía, Madrid', lat: 40.4204, lng: -3.7063,
    hours: 'Selon programme', tags: ['Comédie musicale', 'Gran Vía', 'Populaire'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_48', city: 'Madrid',
    name: 'Matadero Madrid', type: 'Spectacle', neighborhood: 'Legazpi',
    moods: ['Culture', 'Entre amis'], budget: '€',
    description: 'Ancien abattoir reconverti en immense centre culturel. Expos, théâtre, cinéma, marchés… Un quartier culturel à lui seul.',
    address: 'Plaza de Legazpi 8, Madrid', lat: 40.3924, lng: -3.6977,
    hours: 'Mar–Dim 11h–21h', tags: ['Reconverti', 'Pluridisciplinaire', 'Alternatif'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_49', city: 'Madrid',
    name: 'Cinesa Proyecciones', type: 'Cinéma', neighborhood: 'Centro',
    moods: ['Culture', 'Date', 'Tranquille'], budget: '€€',
    description: 'Cinéma du centre de Madrid avec plusieurs salles. Bon pour voir les blockbusters en VO ou les sorties espagnoles.',
    address: 'Callao, Madrid', lat: 40.4196, lng: -3.7064,
    hours: 'Selon programme', tags: ['Cinéma', 'VO disponible', 'Centre'], highlight: false, contributor: 'Pedro',
  },

  // — Marchés —
  {
    id: 'mad_50', city: 'Madrid',
    name: 'Marché de San Miguel', type: 'Marché', neighborhood: 'Centro',
    moods: ['Brunch', 'Entre amis'], budget: '€€',
    description: 'Marché gastronomique dans une belle halle de fonte. Tapas, vins et spécialités espagnoles à déguster debout. Touristique mais délicieux.',
    address: 'Plaza de San Miguel, Madrid', lat: 40.4153, lng: -3.7093,
    hours: 'Lun–Dim 10h–24h', tags: ['Gastronomique', 'Tapas', 'Halle historique'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_51', city: 'Madrid',
    name: 'Mercado de San Antón', type: 'Marché', neighborhood: 'Chueca',
    moods: ['Brunch', 'Tranquille'], budget: '€€',
    description: 'Marché moderne de Chueca sur 3 niveaux avec rooftop bar. Producteurs locaux, food stalls et bar terrasse en haut.',
    address: 'Chueca, Madrid', lat: 40.4225, lng: -3.6966,
    hours: 'Lun–Sam 10h–22h, Dim 10h–21h', tags: ['Rooftop', 'Producteurs locaux', 'Chueca'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_52', city: 'Madrid',
    name: 'Marché de Saint Ildefonse', type: 'Marché', neighborhood: 'Malasaña',
    moods: ['Brunch', 'Entre amis'], budget: '€€',
    description: 'Marché de tapas et street food de Malasaña dans un bel espace. Ambiance jeune et animée, prix raisonnables.',
    address: 'Calle Fuencarral, Malasaña, Madrid', lat: 40.4237, lng: -3.6988,
    hours: 'Lun–Dim 12h–24h', tags: ['Street food', 'Tapas', 'Malasaña'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_53', city: 'Madrid',
    name: 'Mercado Antón Martín', type: 'Marché', neighborhood: 'Lavapiés',
    moods: ['Brunch', 'Tranquille'], budget: '€',
    description: 'Marché de quartier authentique de Lavapiés, peu touristique. Boucheries, poissonneries, et quelques bars à pintxos.',
    address: 'Lavapiés, Madrid', lat: 40.4139, lng: -3.6984,
    hours: 'Lun–Sam 9h–14h30', tags: ['Local', 'Authentique', 'Peu touristique'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_54', city: 'Madrid',
    name: 'Mercado de la Cebada', type: 'Marché', neighborhood: 'La Latina',
    moods: ['Brunch', 'Tranquille'], budget: '€',
    description: 'Grand marché populaire de La Latina avec poissonneries et boucheries. Ambiance locale et authentique madrilène.',
    address: 'La Latina, Madrid', lat: 40.4125, lng: -3.7087,
    hours: 'Lun–Sam 9h–14h30 / 17h–20h30', tags: ['Local', 'La Latina', 'Poissonnerie'], highlight: false, contributor: 'Pedro',
  },

  // — Parcs & Jardins —
  {
    id: 'mad_55', city: 'Madrid',
    name: 'Jardins de Sabatini', type: 'Parc', neighborhood: 'Palacio Real',
    moods: ['Tranquille', 'Brunch', 'Date'], budget: '€',
    description: 'Jardins à la française jouxtant le Palais Royal. Vue imprenable sur la façade du palais, idéal pour une pause verte au cœur de Madrid.',
    address: 'Palacio Real, Madrid', lat: 40.4199, lng: -3.7179,
    hours: 'Lun–Dim 9h–21h (été 23h)', tags: ['Jardins formels', 'Palais Royal', 'Gratuit'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_56', city: 'Madrid',
    name: 'Jardin Botanique Royal', type: 'Parc', neighborhood: 'Paseo del Arte',
    moods: ['Tranquille', 'Date'], budget: '€',
    description: 'Jardin botanique du XVIIIe siècle avec des milliers d\'espèces végétales. Oasis de calme à deux pas du Prado.',
    address: 'Plaza de Murillo, Madrid', lat: 40.4112, lng: -3.6913,
    hours: 'Lun–Dim 10h–21h (hiver 18h)', tags: ['Botanique', 'Historique', 'Calme'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_57', city: 'Madrid',
    name: 'Parc de Saint Isidore', type: 'Parc', neighborhood: 'Madrid Río',
    moods: ['Tranquille', 'Brunch'], budget: '€',
    description: 'Grand parc en terrasse sur les hauteurs de Madrid Río avec vue sur la ville. Très fréquenté lors de la San Isidro en mai.',
    address: 'Madrid Río, Madrid', lat: 40.4003, lng: -3.7166,
    hours: 'Lun–Dim 7h–22h', tags: ['Vue Madrid', 'San Isidro', 'Terrasse'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_58', city: 'Madrid',
    name: 'Palais de Cristal', type: 'Parc', neighborhood: 'Retiro',
    moods: ['Culture', 'Date', 'Tranquille'], budget: '€',
    description: 'Serre en fer et verre de 1887 dans le parc du Retiro, reconvertie en salle d\'expos. L\'un des plus beaux espaces de Madrid, entrée gratuite.',
    address: 'Parque del Retiro, Madrid', lat: 40.4161, lng: -3.6851,
    hours: 'Selon saison', tags: ['Architecture', 'Gratuit', 'Retiro', 'Expos'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_59', city: 'Madrid',
    name: 'Parc d\'Attractions de Madrid', type: 'Parc', neighborhood: 'Casa de Campo',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Parc d\'attractions historique de Madrid dans la Casa de Campo. Attractions familiales et fêtes foraines classiques.',
    address: 'Casa de Campo, Madrid', lat: 40.4184, lng: -3.7389,
    hours: 'Week-end et vacances, 12h–21h', tags: ['Attractions', 'Famille', 'Casa de Campo'], highlight: false, contributor: 'Pedro',
  },

  // — Monuments & Lieux emblématiques —
  {
    id: 'mad_60', city: 'Madrid',
    name: 'Plaza Mayor', type: 'Monument', neighborhood: 'Centro',
    moods: ['Tranquille', 'Culture'], budget: '€',
    description: 'La plaza plus grande et emblématique de Madrid. Arcades du XVIIe siècle, cafés en terrasse et vie de quartier permanente.',
    address: 'Plaza Mayor, Madrid', lat: 40.4153, lng: -3.7024,
    hours: 'Toujours accessible', tags: ['Emblématique', 'Historique', 'Terrasses'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_61', city: 'Madrid',
    name: 'Cathédrale de la Almudena', type: 'Monument', neighborhood: 'Palacio Real',
    moods: ['Tranquille', 'Culture'], budget: '€',
    description: 'Cathédrale néo-gothique face au Palais Royal, la plus récente d\'Europe (consacrée en 1993). Intérieur coloré et crypte impressionnante.',
    address: 'Calle Bailén, Madrid', lat: 40.4156, lng: -3.7147,
    hours: 'Lun–Dim 9h–21h', tags: ['Cathédrale', 'Néo-gothique', 'Crypte'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_62', city: 'Madrid',
    name: 'Palais Royal de Madrid', type: 'Monument', neighborhood: 'Palacio Real',
    moods: ['Culture', 'Tranquille'], budget: '€€',
    description: 'Le plus grand palais royal d\'Europe occidentale en superficie. Collections royales fabuleuses : armures, tableaux, horloges. Vue magnifique depuis les jardins.',
    address: 'Calle Bailén, Madrid', lat: 40.4179, lng: -3.7143,
    hours: 'Lun–Dim 10h–18h (été 20h)', tags: ['Palais', 'Collections royales', 'Vue imprenable'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_63', city: 'Madrid',
    name: 'Templo de Debod', type: 'Monument', neighborhood: 'Argüelles',
    moods: ['Date', 'Tranquille'], budget: '€',
    description: 'Temple égyptien du IIe siècle av. J.-C. offert par l\'Égypte à l\'Espagne. Vue spectaculaire sur le coucher de soleil depuis les jardins alentour.',
    address: 'Parque de la Montaña, Madrid', lat: 40.4239, lng: -3.7174,
    hours: 'Mar–Dim 10h–14h / 18h–20h', tags: ['Égyptien', 'Coucher de soleil', 'Gratuit'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'mad_64', city: 'Madrid',
    name: 'Arènes de Las Ventas', type: 'Monument', neighborhood: 'Las Ventas',
    moods: ['Culture', 'Entre amis'], budget: '€€',
    description: 'La plus grande arène du monde hispanique, chef-d\'œuvre néo-mudéjar. Visitable en dehors des corridas pour découvrir l\'architecture et l\'histoire de la tauromachie.',
    address: 'Las Ventas, Madrid', lat: 40.4317, lng: -3.6625,
    hours: 'Musée : Mar–Ven 10h–17h30, Sam–Dim 10h–13h30', tags: ['Architecture', 'Tauromachie', 'Mudéjar'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_65', city: 'Madrid',
    name: 'Bernabéu', type: 'Stade', neighborhood: 'Chamartín',
    moods: ['Entre amis', 'Culture'], budget: '€€',
    description: 'Le stade mythique du Real Madrid avec sa nouvelle toiture rétractable. Visite guidée impressionnante même hors match.',
    address: 'Chamartín, Madrid', lat: 40.4531, lng: -3.6883,
    hours: 'Lun–Dim 10h–19h (visites)', tags: ['Foot', 'Real Madrid', 'Architecture'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_66', city: 'Madrid',
    name: 'Riyadh Air Metropolitano', type: 'Stade', neighborhood: 'Valdebebas',
    moods: ['Entre amis', 'Festif'], budget: '€€',
    description: 'Le stade de l\'Atlético de Madrid, inauguré en 2017. Enceinte moderne avec une atmosphère électrique les soirs de match.',
    address: 'Avenida de Luis Aragonés, Madrid', lat: 40.4364, lng: -3.7201,
    hours: 'Selon matchs', tags: ['Foot', 'Atlético', 'Moderne'], highlight: false, contributor: 'Pedro',
  },

  // — Magasins —
  {
    id: 'mad_67', city: 'Madrid',
    name: 'Boxer Madrid', type: 'Magasin', neighborhood: 'Chueca',
    moods: ['Tranquille'], budget: '€€',
    description: 'Boutique de vêtements masculins tendance à Chueca. Marques sélectionnées, style soigné.',
    address: 'Chueca, Madrid', lat: 40.4230, lng: -3.6985,
    hours: '–', tags: ['Mode homme', 'Chueca', 'Tendance'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'mad_68', city: 'Madrid',
    name: 'Árbol', type: 'Magasin', neighborhood: 'Malasaña',
    moods: ['Tranquille'], budget: '€€',
    description: 'Boutique de vêtements indépendante à Malasaña avec un beau choix de pièces originales.',
    address: 'Malasaña, Madrid', lat: 40.4248, lng: -3.7048,
    hours: '–', tags: ['Mode', 'Indépendant', 'Malasaña'], highlight: false, contributor: 'Pedro',
  },

  // ══════════════════════════════════════════
  //  PARIS
  // ══════════════════════════════════════════
  {
    id: 'par_01', city: 'Paris',
    name: 'Maison Poincaré', type: 'Musée', neighborhood: 'Latin Quarter',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Musée des mathématiques ouvert en 2023, dédié à rendre les maths accessibles et visuelles. Expos interactives et temporaires de grande qualité.',
    address: 'Latin Quarter, Paris', lat: 48.8477, lng: 2.3435,
    hours: 'Mar–Dim 11h–18h', tags: ['Mathématiques', 'Interactif', 'Récent'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'par_02', city: 'Paris',
    name: 'MuAM – Arts et Métiers', type: 'Musée', neighborhood: 'Marais',
    moods: ['Culture', 'Tranquille'], budget: '€',
    description: 'Musée des techniques et inventions dans une ancienne abbaye. Pendule de Foucault, locomotive à vapeur, machine de Pascal… Un trésor peu fréquenté.',
    address: '60 rue Réaumur, Paris 75003', lat: 48.8657, lng: 2.3555,
    hours: 'Mar–Dim 10h–18h', tags: ['Sciences', 'Inventions', 'Abbaye'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'par_03', city: 'Paris',
    name: 'Palais Galliera', type: 'Musée', neighborhood: 'Trocadéro',
    moods: ['Culture', 'Date'], budget: '€€',
    description: 'Musée de la mode de la Ville de Paris dans un beau palais néo-Renaissance. Expos temporaires sur les grands créateurs et l\'histoire du vêtement.',
    address: '10 avenue Pierre 1er de Serbie, Paris 75116', lat: 48.8659, lng: 2.2967,
    hours: 'Mar–Dim 10h–18h', tags: ['Mode', 'Couture', 'Palais'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'par_04', city: 'Paris',
    name: 'Musée des Arts Décoratifs', type: 'Musée', neighborhood: 'Louvre',
    moods: ['Culture', 'Date', 'Tranquille'], budget: '€€',
    description: 'Collections permanentes de mobilier, bijoux, jouets et mode du Moyen Âge à nos jours. Expos temporaires de grande qualité, aile du Louvre.',
    address: '107 rue de Rivoli, Paris 75001', lat: 48.8634, lng: 2.3342,
    hours: 'Mar–Dim 11h–18h', tags: ['Arts déco', 'Design', 'Bijoux', 'Mode'], highlight: false, contributor: 'Pedro',
  },
  {
    id: 'par_05', city: 'Paris',
    name: 'La REcyclerie', type: 'Restaurant', neighborhood: 'Montmartre',
    moods: ['Brunch', 'Entre amis', 'Tranquille'], budget: '€€',
    description: 'Bar-restaurant écologique dans une ancienne gare de petite ceinture. Potager urbain, compost collectif, brunch bio le week-end. Cadre unique.',
    address: '83 bd Ornano, Paris 75018', lat: 48.8968, lng: 2.3477,
    hours: 'Lun–Ven 8h–22h, Sam–Dim 10h–22h', tags: ['Écologique', 'Brunch', 'Gare reconvertie'], highlight: true, contributor: 'Pedro',
  },
  {
    id: 'par_06', city: 'Paris',
    name: 'Tata Burger', type: 'Restaurant', neighborhood: 'Paris',
    moods: ['Entre amis', 'Tranquille'], budget: '€€',
    description: 'Burger artisanal de qualité, concept simple et bien exécuté. Ingrédients frais et buns maison.',
    address: 'Paris', lat: 48.8588, lng: 2.3527,
    hours: '–', tags: ['Burger', 'Artisanal', 'Produits frais'], highlight: false, contributor: 'Pedro',
  },
];
